### ISSUE TITLE
css for website

### ISSUE THREAD

**Issue by marty-downs** [lter/eco-data-synth-primer#1]
@njlyon0 I'm finding myself using lots of blockquotes and tab structures on the website -- but the contrast for them on this theme is quite low. They are a little difficult for me to distinguish even sitting at my computer with no visual impairment. Is there a way you could tweak the css across the board to darken them up? Thx, Marty

**Comment by njlyon0** [comment]
Block quotes are when you have that small vertical line next to a chunk of text, right? What are tab structures?

The contrast is *a lot* better in the night mode which means it should be doable to mess with it for light mode. You can click the toggle in the top right of the navbar to switch between day and night mode.

**Comment by njlyon0** [comment]
Seems like perhaps we should make a custom SCSS rule (like [here](https://github.com/quarto-dev/quarto-cli/discussions/2879)?). Or does bolding the relevant text work too?

**Comment by njlyon0** [comment]
@marty-downs, I tweaked the light mode background color to be a brighter/colder white. I think the contrast is a bit better but what do you think? I also saw you integrated bolding on some of the text which was a big improvement for contrast I thought!

**Comment by marty-downs** [comment]
It's a little better. Darkening the tabset borders and the quote insets would probably help more, but I don't know what the selectors are for them. Not the highest priority, but if you get a chance to track it down, great.

It's a general issue with GH pages and a little bit of a pet peeve. 

<img width="846" alt="Screenshot 2024-07-29 at 10 17 06 AM" src="https://github.com/user-attachments/assets/8ab987ca-3684-490b-9046-67ea6f949a24">

**Comment by njlyon0** [comment]
Actually, I just did a deep dive on this and I think I fixed it! Rather than darkening the borders, I've changed the background color only of the active tab and its contents relative to the background of the website as a whole. It makes the contrast really sharp even though the lines actually defining the borders are not that visually distinct

**Comment by njlyon0** [comment]
Does the new website look okay to you @marty-downs ?

**Comment by njlyon0** [comment]
Got confirmation in Slack that those changes to the SCSS fixed the contrast issues we were having!
